# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2058344fe70f11cc808ca4d3cbfeeaf43985cf6566955101f69a9b1126c2eabe7debc7cf787d5475e178862727b173c6d6cfa7ded18810642ceda8993316b66a

test:
  secret_key_base: cb53c28100606ad5869f6f340a39ca4bdb61f501eefb90ff58a69e6f37b6c93f2b985361595cf24cce8e37c8efe14a466740fb991cefef25b1d957ac65424430

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
